on:
  workflow_call:
    inputs:
      region:
        description: 'AWS region to mirror images to'
        required: true
        type: string
      environment:
        description: 'Environment to mirror images to'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  sync-images:
    runs-on: ubuntu-latest
    environment: ${{ inputs.region }}-${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_IAM_ROLE_ARN }}
          aws-region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
        with:
          mask-password: 'true'

      - name: Portage Image Sync
        id: portage
        uses: monkescience/portage-action@f0c76792d85addeb97e0f4b068f559d446c49aa9
        with:
          images-file: ${{ inputs.region }}-${{ inputs.environment }}.json

      - name: Output results
        run: |
          echo "Sync Results: ${{ steps.portage.outputs.results }}"
          echo "Success Count: ${{ steps.portage.outputs.success-count }}"
          echo "Total Count: ${{ steps.portage.outputs.total-count }}"
