name: Mirror Images to eu-central-1-prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/mirror-images.yaml
    with:
      region: eu-central-1
      environment: prod
